### PR TITLE
Fix problems not updating as completed properly

### LINKED ISSUE #156: Completed problems are not being marked as completed
When you complete a problem (as in all the test cases are correct), the counter for if the problem was "complete" in the overview (navigation of problems) does not correctly update. Students are not happy about this lol

Using the inspect element, it is the front end that checks the number of correct outputs (when comparing student's code output to the expected otuput). Could we move this calculation to the database? To hopefully make this feature more resilient as it's essential to students' feeling of success and motivation

### LINKED ISSUE #170: Change selectedTopic Varible Name to selectedCategory

### PR DESCRIPTION
**Pull request by guitarwhal**
Fix problems not receiving the green checkmark or grey in-progress sticker without refreshing or browser losing and regaining focus.

Closes #156 
Closes #170

Changes:
- Rename selectedTopic to reflect it referring to the selected category (there was a comment about it, I got sidetracked)
- Move progress and fetchProgress out of ProblemList and up into root
- Pass refetchProgress to useEval to call after solved problems DB write
- Change solvedProblems and uncompletedProblems from `const` to useMemo to update on change
- Change sortProblems to create a new array ([...problemList]) to force a re-render

### CODE REVIEW

File: src/routes/Auth.tsx [hunk 1]
```diff
@@ -58,4 +58,4 @@ export default function Auth() {
       { !!success && <Typography color="success">{success}</Typography> }
     </Stack>
   )
-}
+}
```
Comment (guitarwhal) [inline src/routes/Auth.tsx]: Whoops

File: src/routes/root.tsx [hunk 2]
```diff
@@ -233,9 +238,11 @@ export default function App() {
...
                 </>
               ) : (
-                <Link to="/signin">
-                  <Button>Login</Button>
-                </Link>
+                <>
+                  <Link to="/signin">
+                    <Button>Login</Button>
+                  </Link>
+                </>
```
Comment (guitarwhal) [inline src/routes/root.tsx:256]: Ignore the empty tag, remnant of auth branch (there was a login and register button) itll be back

**Review by Ella1504 — APPROVED** [review]
Looks good!

**Review by AltrosMado — APPROVED** [review]
Look good, for the bug itself does it occur randomly or was it something you could replicate in a controlled way?

Make sure to close the [issue](https://github.com/coding-cat-official/coding-cat/issues/170) that mentions changing the name

**Comment by guitarwhal** [comment]
> Look good, for the bug itself does it occur randomly or was it something you could replicate in a controlled way?

At first, it seemed random but it was a number of things making it inconsistent. The gist was it wouldn't show the problem as "completed" (as in with the checkmark sticker next to it in the problem list) unless you refreshed or tabbed out and back in. I had to grab my changes from my 'auth' branch to log in, I would complete a problem and see when the sticker would appear. Now as soon as the problem is run, a sticker (either the grey in-progress one or the green completed one) will be there next to the problem in the list.

> Make sure to close the [issue](https://github.com/coding-cat-official/coding-cat/issues/170) that mentions changing the name

Added to the desc. and will do.
