### PR TITLE
Fix reflections to Display Reflection Prompts Properly

### LINKED ISSUE #114: Reflection questions don't show up correctly
in the [questions.ts](https://github.com/coding-cat-official/coding-cat/blob/main/src/utils/questions.ts) file, the reflection questions are separated into 2 sets, success and fail, and a random question shows up depending on whether the user successfully solves the problem or not.

currently, when a submission is made, it uses the result of the previous submission to determine which set of questions to ask, so if the user submits an incorrect solution and then a correct one, on that second submission they will see a question from the fail set instead of success, and vice-versa.

### PR DESCRIPTION
**Pull request by AltrosMado**
## Desc

There was a problem where when you solved a coding question incorrectly and then fixed the incorrect solution with a new working one. The reflection questions would not reflect that state properly. For example

Incorrect Solution --> Success Reflection Prompt --> Correct Solution --> Fail Reflection Prompt

The Following issue details my notes in finding a solution to this problem

<https://github.com/coding-cat-official/coding-cat/issues/114>

Closes Issue #114

### CODE REVIEW

**Comment by thomas-kol** [comment]
Watch out, you're merging into main!

**Comment by AltrosMado** [comment]
> Watch out, you're merging into main!

Thanks for the catch!

File: src/hooks/useEval.tsx [hunk 1]
```diff
@@ -11,13 +11,18 @@ export default function useEval(problem: Problem, session: Session | null, refet
     const [evalResponse, setEvalResponse] = useState<EvalResponse | null>(null)
     const currentCodeRef = useRef<string>('');
 
-    useEffect(() => { setEvalResponse(null); }, [problem]);
+    // Set eval response to null every time the problem changes
```
Comment (thomas-kol) [inline src/hooks/useEval.tsx:14]: Question: Is the reflection progress saved anywhere if it's incomplete? (such as into supabase or local storage)

**Review by Vysan13 — APPROVED** [review]
Looks good!

**Review by thomas-kol — APPROVED** [review]
Looks good to go!

File: src/hooks/useEval.tsx (hunk 1 above)
Comment (AltrosMado) [reply src/hooks/useEval.tsx:14]: Not the progress. When you write a reflection and post it. It gets saved in the reflection column of the Submissions table in the db. If a user does not submit a reflection, that reflection column has null instead.
